[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin_odoo_2026
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_secret_2026
db_name = odoo_erp_commercial
list_db = False
log_level = warn

; --- Optimisation pour Azure B1s (1 Go RAM) ---
limit_memory_hard = 536870912
limit_memory_soft = 419430400
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1
workers = 2

; --- Proxy mode (derrière Nginx) ---
proxy_mode = True
